### ISSUE TITLE
Tables from modules have lenght 0 but are accessible component-wise

### ISSUE THREAD

**Issue by ParadoxTrWe** [COVESA/ramses-logic#38]
Suppose we define a module:

```
local coalaModule = {}

coalaModule.coalaColor = {1.0, 0.0, 0.0}    -- red

return coalaModule
```

and use it in a script to, for example, set the OUT.Color property:

```
modules("coalas")

function interface()
    OUT.Color = VEC3F
    OUT.Color_Length = INT
    OUT.Color_Type = STRING
end

function run()
    OUT.Color_Length = #coalas.coalaColor
    OUT.Color_Type = tostring(type(coalas.coalaColor))
    
    -- this throws an error: "Error while extracting array: expected 3 array components in table but got 0 instead!":
    OUT.Color = coalas.coalaColor
    
    -- this, however, works fine:
    OUT.Color = {coalas.coalaColor[1], coalas.coalaColor[2], coalas.coalaColor[3]}  
end
```

As you can see, the Table "coalaColor" can be used, if the components are accessed individually, but as soon as we try accessing the whole Table, it has a lenght of 0. Using local variables before assigning it to the OUT.Color produces the same error as directly assigning it from the module.

(The same can be observed when using VEC2F or VEC4F with 2- or 4-dimensional tables, respectively)

**Comment by violinyanev** [comment]
Hi! Thanks for the report, but it's been fixed in the 0.14.0 release. Try it! ;)
